[feature]: Add support for target type in anchor tag xhtml
samclarke/SCEditor pull request #843
Opened 2021-08-13 15:27 UTC by jtoloui-ibm

# Add support for target type in anchor tag xhtml

## To support target type in xhtml links
- Included select option: _blank, _self, _top, _parent

2021-08-13 19:47 UTC, live627 commented on src/formats/bbcode.js
> +					content + '</a>');
```suggestion
```

2021-08-13 21:38 UTC, samclarke requested changes
Thanks for the PR!

Could you turn off the auto-formatting? All the white space changes make it very difficult to see what's changed.

This won't be able to be merged until the next breaking as this wouldn't be backwards compatible (not all BBCode parser support targets). If you want to make it into a plugin it could be added now otherwise it will have to wait until the next breaking release.

I'm aiming to get as many bugs fixed as possible before the next breaking release. I'm currently planning to go through all the PRs and sort them out in a few weeks and then release another 3.x version. Hopefully, after that it will only take one more release of bug fixes before a new breaking release.

2021-08-16 08:17 UTC, jtoloui-ibm commented
> Thanks for the PR!
> 
> Could you turn off the auto-formatting? All the white space changes make it very difficult to see what's changed.
> 
> This won't be able to be merged until the next breaking as this wouldn't be backwards compatible (not all BBCode parser support targets). If you want to make it into a plugin it could be added now otherwise it will have to wait until the next breaking release.
> 
> I'm aiming to get as many bugs fixed as possible before the next breaking release. I'm currently planning to go through all the PRs and sort them out in a few weeks and then release another 3.x version. Hopefully, after that it will only take one more release of bug fixes before a new breaking release.

Sorry, I'll sort out the formatting and also look into creating a plugin if that would make it easier rather to wait for the next major release. 

One question would be, if I go with the plugin route, would you recommend still trying to support BBCode or recommend just creating an xhtml link plugin?

2021-08-19 09:53 UTC, jtoloui-ibm commented
Hey @samclarke I've recreated this PR as you suggested in a plugin version #844

2021-09-30 17:45 UTC, samclarke commented
Closing this in favour of the plugin version #844.

2021-09-30 17:45 UTC, closed without merging